### GET Tranaction 

GET http://localhost:8082/api/v2/transaction HTTP/1.1


### Create Tranaction 
POST http://localhost:8082/api/v2/transaction HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTE1MTkyMzQsImlkIjoyMSwibGV2ZWwiOiJub3JtYWwiLCJ1c2VybmFtZSI6Ik5FVzA5In0.U0sT3GkKm-Nx5G3qvBgftZ9pstdTe-Bjr6BgOX9JZjI

{
  "total": 300,
  "paid": 200,
  "change": 100,
  "payment_type": "cash",
  "payment_detail": "full",
  "order_list": "[]",
  "StaffID" : 4
}

### Create Tranaction with token
POST http://localhost:8082/api/v2/transaction HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTE1MTkyMzQsImlkIjoyMSwibGV2ZWwiOiJub3JtYWwiLCJ1c2VybmFtZSI6Ik5FVzA5In0.U0sT3GkKm-Nx5G3qvBgftZ9pstdTe-Bjr6BgOX9JZjI

{
  "total": 500,
  "paid": 400,
  "change": 100,
  "payment_type": "cash",
  "payment_detail": "full",
  "order_list": "[]" 
}

